name: tests
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.22.3
      - uses: actions/checkout@v2
      - name: test
        run: make test